# Lecture 2 – Data 100, Spring 2026

[Acknowledgments Page](https://ds100.org/sp26/acks/)

A high-level overview of the [`pandas`](https://pandas.pydata.org) library to accompany Lecture 2.

In [2]:
# `pd` is the conventional alias for Pandas, as `np` is for NumPy
import pandas as pd

## Series, DataFrames, and Indices

Series, DataFrames, and Indices are fundamental `pandas` data structures for storing tabular data and processing the data using vectorized operations.

### Series

A `Series` is a 1-D labeled array of data. We can think of it as columnar data. 

Let's create a `Series` object and look at its two components: 1) values and 2) index.

In [3]:
s = pd.Series(["welcome", "to", "data 100"])
s

0     welcome
1          to
2    data 100
dtype: object

In [4]:
s.values

array(['welcome', 'to', 'data 100'], dtype=object)

In [5]:
# this is a more efficient way of representing [0, 1, 2]
s.index

RangeIndex(start=0, stop=3, step=1)

In the example above, `pandas` automatically generated an `Index` of integer labels. We can also create a `Series` object by providing a custom `Index`.

In [6]:
s = pd.Series([-1, 10, 2], index=["a", "b", "c"])
s

a    -1
b    10
c     2
dtype: int64

In [7]:
s.values

array([-1, 10,  2])

In [8]:
s.index

Index(['a', 'b', 'c'], dtype='object')

After it has been created, we can reassign the Index of a `Series` to a new Index.

In [9]:
s.index = ["first", "second", "third"]
s

first     -1
second    10
third      2
dtype: int64

#### Selection in Series
We can select a single value or a set of values in a `Series` using:
- A single label
- A list of labels
- A filtering condition using a **Boolean mask**

In [10]:
s = pd.Series([4, -2, 0, 6], index=["a", "b", "c", "d"])
s

a    4
b   -2
c    0
d    6
dtype: int64

**Selection using one or more label(s)**

In [11]:
# Selection using a single label
# Notice how the return value is a single array element
s["a"]

4

In [12]:
# Selection using a list of labels
# Notice how the return value is another Series
s[["a", "c"]]

a    4
c    0
dtype: int64

**Selection using a filter condition**

In [13]:
# Boolean mask: true for all elements greater than 0.
s > 0

a     True
b    False
c    False
d     True
dtype: bool

In [15]:
s + 4

a     8
b     2
c     4
d    10
dtype: int64

In [14]:
# Use the Boolean mask to select data from the original Series: this picks all entries greater than 0
s[s > 0]

a    4
d    6
dtype: int64

<br><br><br><br><br><br><br>
**Instructor Note: Return to slides!**
<br><br><br><br><br><br><br>

#### DataFrame

A `DataFrame` is a 2-D tabular data structure with both row and column labels. In this lecture, we will see how a `DataFrame` can be created from scratch or loaded from a file. We'll cover the following:
1. From a CSV file
2. From a list of rows
3. From a dictionary of columns
4. From a `Series`

(but there are many more!)

##### Creating a `DataFrame` from a CSV file
For loading data into a `DataFrame`, `pandas` has a number of very useful file reading tools. We'll be using `read_csv` today to load data from a CSV file into a `DataFrame` object.

In [17]:
elections = pd.read_csv("data/elections.csv")
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
182,2024,Donald Trump,Republican,77303568,win,49.808629
183,2024,Kamala Harris,Democratic,75019230,loss,48.336772
184,2024,Jill Stein,Green,861155,loss,0.554864
185,2024,Robert Kennedy,Independent,756383,loss,0.487357
186,2024,Chase Oliver,Libertarian Party,650130,loss,0.418895

By passing a column to the `index_col` attribute, the `Index` can be defined at the initialization.

In [ ]:
elections = pd.read_csv("data/elections.csv", index_col="Candidate")
elections

In [18]:
elections = pd.read_csv("data/elections.csv", index_col="Year")
elections

              Candidate                  Party  Popular vote Result          %
Year
1824     Andrew Jackson  Democratic-Republican        151271   loss  57.210122
1824  John Quincy Adams  Democratic-Republican        113142    win  42.789878
1828     Andrew Jackson             Democratic        642806    win  56.203927
1828  John Quincy Adams    National Republican        500897   loss  43.796073
1832     Andrew Jackson             Democratic        702735    win  54.574789
...                 ...                    ...           ...    ...        ...
2024       Donald Trump             Republican      77303568    win  49.808629
2024      Kamala Harris             Democratic      75019230   loss  48.336772
2024         Jill Stein                  Green        861155   loss   0.554864
2024     Robert Kennedy            Independent        756383   loss   0.487357
2024       Chase Oliver      Libertarian Party        650130   loss   0.418895

[187 rows x 5 columns]

##### Creating a `DataFrame` from a list of rows

In [19]:
# Creating a DataFrame from a list of rows
# Each row is a list, and we specify column names
df_list_1 = pd.DataFrame(
    [["Kiwi", 5.49],
     ["Orange", 3.99]],
    columns=["Fruit", "Price"]
)
df_list_1

    Fruit  Price
0    Kiwi   5.49
1  Orange   3.99

In [20]:
# Creating a DataFrame from a list of rows
# Each row is a dictionary
df_list_2 = pd.DataFrame(
    [{"Fruit": "Kiwi", "Price": 5.49}, 
     {"Fruit": "Orange", "Price": 3.99}]
)
df_list_2

    Fruit  Price
0    Kiwi   5.49
1  Orange   3.99

##### Creating a `DataFrame` from a dictionary of columns

In [21]:
# Creating a DataFrame from a dictionary of columns
# where each columns is a *list*:
df_dict_1 = pd.DataFrame(
    {"Fruit": ["Kiwi", "Orange"], 
     "Price": [5.49, 3.99]}
)
df_dict_1

    Fruit  Price
0    Kiwi   5.49
1  Orange   3.99

In [22]:
# first, make some Series
ser_a = pd.Series(["a1", "a2", "a3"], index=["r1", "r2", "r3"])
ser_b = pd.Series(["b1", "b2", "b3"], index=["r1", "r2", "r3"])
ser_a

r1    a1
r2    a2
r3    a3
dtype: object

In [23]:

# Creating a DataFrame from a dictionary of columns
# where each column is a *Series* (must have matching Indexes)
df_dict_ser = pd.DataFrame(
    {"ColumnA": ser_a, "ColumnB": ser_b}
)
df_dict_ser

   ColumnA ColumnB
r1      a1      b1
r2      a2      b2
r3      a3      b3

##### Creating a `DataFrame` from a `Series`

In [24]:
# Passing a Series to the DataFrame constructor to make a one-column DataFrame
df_ser = pd.DataFrame(ser_a)
df_ser

     0
r1  a1
r2  a2
r3  a3

In [25]:
# Using to_frame() to convert a Series to DataFrame
ser_to_df = ser_a.to_frame()
ser_to_df

     0
r1  a1
r2  a2
r3  a3

#### `DataFrame` attributes: `index`, `columns`, and `shape`

In [ ]:
# Creating a DataFrame from a CSV file and specifying the Index column
elections = pd.read_csv("data/elections.csv", index_col="Candidate")
elections

In [ ]:
elections.index

In [ ]:
elections.columns

In [ ]:
elections.shape

<br><br><br><br><br><br><br>
**Instructor Note: Return to slides!**
<br><br><br><br><br><br><br>

### Extracting data from `DataFrame`s

In [26]:
elections = pd.read_csv('data/elections.csv')
elections

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
182,2024,Donald Trump,Republican,77303568,win,49.808629
183,2024,Kamala Harris,Democratic,75019230,loss,48.336772
184,2024,Jill Stein,Green,861155,loss,0.554864
185,2024,Robert Kennedy,Independent,756383,loss,0.487357
186,2024,Chase Oliver,Libertarian Party,650130,loss,0.418895

We can use `.head` to return only a few rows of a dataframe.

In [ ]:
# By default, calling .head with no argument will show the first 5 rows
elections.head()

In [27]:
elections.head(3)

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927

We can also use `.tail` to get the last so many rows.

In [28]:
elections.tail(5)

     Year       Candidate              Party  Popular vote Result          %
182  2024    Donald Trump         Republican      77303568    win  49.808629
183  2024   Kamala Harris         Democratic      75019230   loss  48.336772
184  2024      Jill Stein              Green        861155   loss   0.554864
185  2024  Robert Kennedy        Independent        756383   loss   0.487357
186  2024    Chase Oliver  Libertarian Party        650130   loss   0.418895

*What might be some issues with using `.head` or `.tail` to check a DataFrame?*

#### Label-Based Extraction Using `.loc`

`.loc` uses two arguments, one for row labels and one for column labels. Each argument to `.loc` can be:
1. A single value.
2. A list.
3. A slice (syntax is **inclusive** of the right-hand side of the slice, unlike normal Python indexing).
3. A boolean mask

`loc` selects items by row and column *label*.

In [29]:
# Selection by a row label and a column label
elections.loc[0, "Candidate"]

'Andrew Jackson'

In [30]:
# Selection by a list
elections.loc[[87, 25, 179], ["Year", "Party", "%"]]

     Year                Party          %
87   1932           Republican  39.830594
25   1860  Southern Democratic  18.138998
179  2020           Republican  46.858542

In [31]:
# Selection by a list and a slice of columns
elections.loc[[87, 25, 179], "Popular vote":"%"]

     Popular vote Result          %
87       15761254   loss  39.830594
25         848019   loss  18.138998
179      74216154   loss  46.858542

In [ ]:
# Extracting all rows using a colon
elections.loc[:, ["Year", "Candidate", "Result"]]

In [32]:
# Extracting all columns using a colon
elections.loc[[87, 25, 179], :]

,Year,Candidate,Party,Popular vote,Result,%
87,1932,Herbert Hoover,Republican,15761254,loss,39.830594
25,1860,John C. Breckinridge,Southern Democratic,848019,loss,18.138998
179,2020,Donald Trump,Republican,74216154,loss,46.858542

In [ ]:
# Selection by a list and a single-column label
elections.loc[[87, 25, 179], "Popular vote"]

In [42]:
# Note that if we pass "Popular vote" in a list, the output will be a DataFrame
elections.loc[[87, 25, 179], ["Popular vote"]]

     Popular vote
87       15761254
25         848019
179      74216154

In [46]:
# Selection with a boolean mask
elections.loc[elections["Year"] == 2020, ["Year", "Candidate"]]

     Year       Candidate
178  2020    Joseph Biden
179  2020    Donald Trump
180  2020    Jo Jorgensen
181  2020  Howard Hawkins

In [ ]:
# If we only use one argument for .loc, pandas uses it
#  for the rows and returns all columns
elections.loc[[180, 181]]

<br><br><br><br><br><br><br>
**Instructor Note: Return to slides!**
<br><br><br><br><br><br><br>

#### Integer-Based Extraction Using `iloc`

`iloc` selects items by row and column *integer* position.

Arguments to `.iloc` can be:
1. A single value.
2. A list.
3. A slice (syntax is **exclusive** of the right hand side of the slice, just like with lists/arrays/etc.).

In [63]:
# Extracting the value at the first row (row 0) and the second column.
# Remember that Python indexing begins at position 0!
elections.iloc[0,1]

'Andrew Jackson'

In [ ]:
# Extracting the second, third, and fourth rows of the second column
# (returns a series since we used a single column)
elections.iloc[[1, 2, 3], 1]

In [ ]:
# Select the rows at positions 1, 2, and 3.
# Select the columns at positions 0, 1, and 2.
elections.iloc[[1, 2, 3], [0, 1, 2]]

In [64]:
# Index-based extraction using a list of rows and a slice of column indices
elections.iloc[[1, 2, 3], 0:3]

   Year          Candidate                  Party
1  1824  John Quincy Adams  Democratic-Republican
2  1828     Andrew Jackson             Democratic
3  1828  John Quincy Adams    National Republican

In [65]:
# Selecting all rows using a colon
elections.iloc[:, 0:3]

     Year          Candidate                  Party
0    1824     Andrew Jackson  Democratic-Republican
1    1824  John Quincy Adams  Democratic-Republican
2    1828     Andrew Jackson             Democratic
3    1828  John Quincy Adams    National Republican
4    1832     Andrew Jackson             Democratic
..    ...                ...                    ...
182  2024       Donald Trump             Republican
183  2024      Kamala Harris             Democratic
184  2024         Jill Stein                  Green
185  2024     Robert Kennedy            Independent
186  2024       Chase Oliver      Libertarian Party

[187 rows x 3 columns]

In [66]:
# If we only use one argument for .iloc, pandas uses it
# for the rows, and returns all columns
elections.iloc[138:144]

     Year          Candidate        Party  Popular vote Result          %
138  1988           Ron Paul  Libertarian        431750   loss   0.472660
139  1992       Andre Marrou  Libertarian        290087   loss   0.278516
140  1992       Bill Clinton   Democratic      44909806    win  43.118485
141  1992           Bo Gritz     Populist        106152   loss   0.101918
142  1992  George H. W. Bush   Republican      39104550   loss  37.544784
143  1992         Ross Perot  Independent      19743821   loss  18.956298

<br><br><br><br><br><br><br>
**Instructor Note: Return to slides!**
<br><br><br><br><br><br><br>

#### Context-dependent Extraction using `[]`

We can do anything we want using `loc` or `iloc`. However, in practice, the `[]` operator is often used instead to yield more concise code for the most common `DataFrame` manipulations.

`[]` is a bit trickier to understand than `loc` or `iloc`, but it achieves some of the same functionality. The most important difference is that `[]` is *context-dependent*.

Remember that `.loc` and `.iloc` always take two arguments: the row labels and the column labels (and if you only pass one argument, it's always used as the row labels).

`[]` only takes one argument, which could be used for rows **or** labels, depending on what the argument is:
1. If it's a **single label**, it's treated as a **column** label (like with `loc`)
2. If it's a **list**, it's treated as **column** labels (like with `loc`)
3. If it's a **slice**, it's treated as **integer row** labels (like with `iloc`)
4. If it's a **boolean mask**, it's treated as **row** labels (like with `loc`)

In [68]:
# If we provide a single column name, we get back that column as a Series
elections["Candidate"]

0         Andrew Jackson
1      John Quincy Adams
2         Andrew Jackson
3      John Quincy Adams
4         Andrew Jackson
             ...
182         Donald Trump
183        Kamala Harris
184           Jill Stein
185       Robert Kennedy
186         Chase Oliver
Name: Candidate, Length: 187, dtype: object

In [69]:
# If we provide a list of column names, we get the listed columns.
elections[["Year", "Candidate", "Result"]]

     Year          Candidate Result
0    1824     Andrew Jackson   loss
1    1824  John Quincy Adams    win
2    1828     Andrew Jackson    win
3    1828  John Quincy Adams   loss
4    1832     Andrew Jackson    win
..    ...                ...    ...
182  2024       Donald Trump    win
183  2024      Kamala Harris   loss
184  2024         Jill Stein   loss
185  2024     Robert Kennedy   loss
186  2024       Chase Oliver   loss

[187 rows x 3 columns]

In [70]:
# If we provide a slice of row numbers, we get the numbered rows.
elections[3:7]

,Year,Candidate,Party,Popular vote,Result,%
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
5,1832,Henry Clay,National Republican,484205,loss,37.603628
6,1832,William Wirt,Anti-Masonic,100715,loss,7.821583

In [71]:
# If we provide a boolean mask, we get the corresponding rows
elections[elections["Popular vote"] > 60000000]

     Year        Candidate       Party  Popular vote Result          %
157  2004   George W. Bush  Republican      62040610    win  50.771824
162  2008     Barack Obama  Democratic      69498516    win  53.023510
168  2012     Barack Obama  Democratic      65915795    win  51.258484
171  2012      Mitt Romney  Republican      60933504   loss  47.384076
173  2016     Donald Trump  Republican      62984828    win  46.407862
176  2016  Hillary Clinton  Democratic      65853514   loss  48.521539
178  2020     Joseph Biden  Democratic      81268924    win  51.311515
179  2020     Donald Trump  Republican      74216154   loss  46.858542
182  2024     Donald Trump  Republican      77303568    win  49.808629
183  2024    Kamala Harris  Democratic      75019230   loss  48.336772

<br><br><br><br><br><br><br>
**Instructor Note: Return to slides!**
<br><br><br><br><br><br><br>

#### Boolean Operators

To filter on multiple conditions, we combine boolean masks using **bitwise comparisons**.

Symbol | Usage      | Meaning 
------ | ---------- | -------------------------------------
~    | ~p       | Returns negation of p
&#124; | p &#124; q | p OR q
&    | p & q    | p AND q
^  | p ^ q | p XOR q (exclusive or)

**Always** make sure you wrap each condition inside `()` when combining boolean masks with bitwise comparisons!

In [ ]:
# Grab rows from 2008 OR candidates winning over 60% of the vote (or both)
elections[(elections["Year"] == 2008) | (elections["%"] >= 60)]

In [ ]:
# Don't do this! Python's precedence rules (like PEMDAS for other operators) will do the wrong thing
# elections[elections["Year"] == 2008 | elections["%"] >= 60]

In [ ]:
# Grab post-2000 winners: rows where year is after 2000 AND result is win
elections[(elections["Year"] > 2000) & (elections["Result"] == "win")]

In [72]:
# To make code more readable, use multiple lines
elections[(
    (elections["Year"] < 2000) &
    (elections["Year"] > 1941) &
    (elections["Result"] == "win") &
    (elections["%"] >= 55)
)]

     Year          Candidate       Party  Popular vote Result          %
106  1952  Dwight Eisenhower  Republican      34075529    win  55.325173
109  1956  Dwight Eisenhower  Republican      35579180    win  57.650654
114  1964     Lyndon Johnson  Democratic      43127041    win  61.344703
120  1972      Richard Nixon  Republican      47168710    win  60.907806
133  1984      Ronald Reagan  Republican      54455472    win  59.023326

#### Preparing the data for our graph

![](images/graph_and_df.png)

We need rows that are either Democratic OR Republican, AND after 1900. We also need only the Year, Party, and % columns.

In [ ]:
# Notice the parens: it's important to use ((dem | rep) & year) so that we
# get the boolean operations right
elections.loc[
    (
        ((elections['Party'] == 'Democratic') | (elections['Party'] == 'Republican')) &
        (elections['Year'] > 1900)
    ),
    ['Year', 'Party', '%']
]

##### Investigating 1992

In [ ]:
# What happened in 1992?
elections[elections['Year'] == 1992]

In [ ]:
# How do we put that in context? How does 19% compare to other third party candidates?
third_party = elections[
    (elections['Party'] != "Democratic") & 
    (elections['Party'] != "Republican") & 
    (elections['Year'] > 1900)
]
third_party.sort_values('%').iloc[-15:, :]

#### Working with the `Index`

We can manipulate the index of a `DataFrame` by using `set_index` and `reset_index`:

In [ ]:
# Creating a DataFrame from a CSV file and specifying the Index column
elections = pd.read_csv("data/elections.csv", index_col="Candidate")
elections.head(3)

The `Index` column can be set to the default list of integers by calling `reset_index()` on a `DataFrame`.

In [ ]:
# reset_index moves the old index to a column and changes the index to the default
elections.reset_index()

In [ ]:
# Notice that reset_index, just like most DataFrame methods, returns a new dataframe (instead of modifying it)
elections

In [ ]:
# This sets the Index to the "Party" column (and deletes the old index!)
elections.set_index("Party")

## Slido Exercises

**Question 1**

What's the output of the following code?

In [16]:
example = pd.Series(
    [4, 5, 6], 
    index=["one", "two", "three"]
)
example[example > 4].values

array([5, 6])

**Questions 2, 3, and 4**

Which of the following statements correctly return the value "blue fish" from the "weird" DataFrame?

In [52]:
weird = pd.DataFrame({"a":["one fish", "two fish"], 
                      "b":["red fish", "blue fish"]})
weird

          a          b
0  one fish   red fish
1  two fish  blue fish

In [ ]:
# weird.loc[1, 1]

In [58]:
weird

          a          b
0  one fish   red fish
1  two fish  blue fish

In [60]:
weird.loc[1, 'b']

'blue fish'

In [ ]:
weird

In [ ]:
# weird.loc[[1,1]]

In [ ]:
weird

In [ ]:
# weird.loc[[1,'b']]

In [ ]:
weird

In [ ]:
# weird.iloc[1, 1]

In [ ]:
weird

In [ ]:
# weird.iloc[1, :]

In [ ]:
weird

In [ ]:
# weird.iloc[2,2]

In [ ]:
weird

In [ ]:
# weird.iloc[0,'b']

In [ ]:
weird

In [61]:
weird[1]['b']

KeyError: 1

In [ ]:
weird

In [62]:
weird['b'][1]

'blue fish'

In [ ]:
weird

In [54]:
weird[1,'b']

KeyError: (1, 'b')

In [ ]:
weird

In [67]:
weird[[1,'b']]

KeyError: '[1] not in index'