# 🎲 Lecture 17 – Data 100, Fall 2025

Data 100, Fall 2025

[Acknowledgments Page](https://ds100.org/fa25/acks/)

In [51]:
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

plt.rcParams['figure.dpi'] = 300


---

## A Random Variable $X$

> This section just replicates figures in the lecture. We won't go through it together.

Our probability distribution of $X$, shown as a table:

In [52]:
# Our random variable X
dist_df = pd.DataFrame({"x": [3, 4, 6, 8],
                        "P(X = x)": [0.1, 0.2, 0.4, 0.3]})
dist_df

   x  P(X = x)
0  3       0.1
1  4       0.2
2  6       0.4
3  8       0.3

In [53]:
fig = px.bar(dist_df, x="x", y="P(X = x)", title="Distribution of X")
# fig.write_image("distX.png", "png",scale=2)
fig

Let's use this probability distribution to generate a table of $X_i$'s (i.e., simulated draws from the probability distirbution above).

In [54]:
N = 80000
samples = np.random.choice(
    dist_df["x"], # Draw from these choiecs
    size=N, # This many times
    p=dist_df["P(X = x)"]) # According to this distribution

sim_df = pd.DataFrame({"X": samples})
sim_df

       X
0      6
1      6
2      8
3      6
4      6
...   ..
79995  6
79996  3
79997  6
79998  6
79999  6

[80000 rows x 1 columns]

<br/><br/>
Let's check how well this simulated sample matches our probability distribution!

In [55]:
fig = px.histogram(sim_df, x="X", title="Empirical distribution of X", 
                   histnorm="probability")
# fig.write_image("empirical_dist.png", "png",scale=2)
fig

In [56]:
print("Simulated E[X]:", sim_df['X'].mean())
print("Simulated Var[X]:", sim_df['X'].var())

Simulated E[X]: 5.8924625
Simulated Var[X]: 2.902534467774597

In [57]:
E_x = dist_df["x"] @ dist_df["P(X = x)"]
print("E[X]:",E_x)

E[X]: 5.9

In [58]:
Var_x = dist_df["x"]**2 @ dist_df["P(X = x)"] - E_x**2
print("Var[X]:", Var_x)

Var[X]: 2.8900000000000006

<br/><br/>

---

# 🎲 🎲 Sum of 2 Dice Rolls

> Here's where the lecture demo starts!

Here's the distribution of a single die roll:

In [59]:
roll_df = pd.DataFrame({"x": [1, 2, 3, 4, 5, 6],
                        "P(X = x)": np.ones(6)/6})
roll_df

   x  P(X = x)
0  1  0.166667
1  2  0.166667
2  3  0.166667
3  4  0.166667
4  5  0.166667
5  6  0.166667

In [60]:
fig = px.bar(roll_df, x="x", y="P(X = x)", title="Distribution of X")
# fig.write_image("die.png", "png",scale=2)
fig.update_layout(
    font=dict(
        size=22,  # Adjust this value for desired font size
    )
)
fig

In [61]:
double_roll_df = pd.DataFrame({"2 * x1": np.arange(2,13,1),
                        "P(2 * X1 = 2 * x1)": [1/6,0,1/6,0,1/6,0,1/6,0,1/6,0,1/6]})
double_roll_df

    2 * x1  P(2 * X1 = 2 * x1)
0        2            0.166667
1        3            0.000000
2        4            0.166667
3        5            0.000000
4        6            0.166667
5        7            0.000000
6        8            0.166667
7        9            0.000000
8       10            0.166667
9       11            0.000000
10      12            0.166667

In [62]:
fig = px.bar(double_roll_df, x="2 * x1", y="P(2 * X1 = 2 * x1)", title="Distribution of 2 * X1")
# fig.write_image("die.png", "png",scale=2)
fig.update_layout(
    font=dict(
        size=18,  # Adjust this value for desired font size
    ),
    xaxis=dict(
            tickmode='linear',  # Generate ticks at regular intervals
            dtick=1             # Set the interval between ticks to 1 (for every value)
        )
)
fig

In [63]:
two_roll_df = pd.DataFrame({"x1+x2": np.arange(2,13),
                        "P(X1+X2 = x1+x2)": np.array([1,2,3,4,5,6,5,4,3,2,1])/36})
two_roll_df

    x1+x2  P(X1+X2 = x1+x2)
0       2          0.027778
1       3          0.055556
2       4          0.083333
3       5          0.111111
4       6          0.138889
5       7          0.166667
6       8          0.138889
7       9          0.111111
8      10          0.083333
9      11          0.055556
10     12          0.027778

In [64]:
fig = px.bar(two_roll_df, x="x1+x2", y="P(X1+X2 = x1+x2)", title="Distribution of X1+X2")
# fig.write_image("die.png", "png",scale=2)
fig.update_layout(
    font=dict(
        size=18,  # Adjust this value for desired font size
    ),
    xaxis=dict(
            tickmode='linear',  # Generate ticks at regular intervals
            dtick=1             # Set the interval between ticks to 1 (for every value)
        )
)
fig

Let $X_1, X_2$ are the outcomes of two dice rolls. Note $X_1$ and $X_2$ are i.i.d. (independent and identically distributed).

Below, we simulate an 80,000-row table of $X_1, X_2$ values. 

The code uses `np.random.choice(arr, size, p)` ([documentation](https://numpy.org/doc/stable/reference/random/generated/numpy.random.choice.html)) where `arr` is the array the values and `p` is the probability associated with choosing each value.

In [65]:
N = 80000

# roll_df["x"] are the values 1 through 6
# roll_df["P(X=x)"] is a column of a constant 1/6, since all faces are 
# equally likely
sim_rolls_df = pd.DataFrame({
    "X_1": np.random.choice(roll_df["x"], size = N, p = roll_df["P(X = x)"]),
    "X_2": np.random.choice(roll_df["x"], size = N, p = roll_df["P(X = x)"])
})

sim_rolls_df

       X_1  X_2
0        5    5
1        2    2
2        6    2
3        2    4
4        6    3
...    ...  ...
79995    4    4
79996    6    2
79997    1    3
79998    1    3
79999    3    5

[80000 rows x 2 columns]

We can use our simulated values of $X_1, X_2$ to create new columns $2 X_1$ and $X_1 + X_2$:

In [66]:
sim_rolls_df['2 X_1'] = 2 * sim_rolls_df['X_1']
sim_rolls_df['X_1 + X_2'] = sim_rolls_df['X_1'] + sim_rolls_df['X_2']
sim_rolls_df

       X_1  X_2  2 X_1  X_1 + X_2
0        5    5     10         10
1        2    2      4          4
2        6    2     12          8
3        2    4      4          6
4        6    3     12          9
...    ...  ...    ...        ...
79995    4    4      8          8
79996    6    2     12          8
79997    1    3      2          4
79998    1    3      2          4
79999    3    5      6          8

[80000 rows x 4 columns]

Now that we have simulated samples of $2 X_1$ and $X_1 + X_2$, we can plot histograms to see their distributions:

In [67]:
plot_df = sim_rolls_df[["2 X_1", "X_1 + X_2"]].melt()

# Show 5 random rows of plot_df
display(plot_df.sample(5))

px.histogram(
  plot_df,
  x="value", 
  color="variable", 
  barmode="overlay", 
  histnorm="probability",
  title="Empirical Distributions"
)

         variable  value
51535       2 X_1      6
104149  X_1 + X_2      2
21920       2 X_1     10
61456       2 X_1      4
127516  X_1 + X_2      5

In [68]:
# The empirical means are nearly identical, but the variance
# of the two rolls is lower than doubling the first roll.
pd.DataFrame([
    sim_rolls_df[["2 X_1", "X_1 + X_2"]].mean().rename("Mean"),
    sim_rolls_df[["2 X_1", "X_1 + X_2"]].var().rename("Var"),
    np.sqrt(sim_rolls_df[["2 X_1", "X_1 + X_2"]].var()).rename("SD")
])

          2 X_1  X_1 + X_2
Mean   7.020250   7.017137
Var   11.639735   5.812691
SD     3.411706   2.410952

<br/><br/>

---

# Which would you pick?

> This is a similar demonstration to the double dice roll above. We won't cover it together during the lecture.

* $\large Y_A = 10 X_1 + 10 X_2 $
* $\large Y_B = \sum\limits_{i=1}^{20} X_i$
* $\large Y_C = 20 X_1$

First let's construct the probability distribution for a single coin. This will let us flip 20 IID coins later.

In [69]:
# First construct probability distribution for a single fair coin
p = 0.5
coin_df = pd.DataFrame({"x": [1, 0], # [Heads, Tails]
                        "P(X = x)": [p, 1 - p]})
coin_df

   x  P(X = x)
0  1       0.5
1  0       0.5

## Choice A:
$\large Y_A = 10 X_1 + 10 X_2 $

In [70]:
N = 10000

np.random.rand(N,2) < p

array([[False, False],
       [ True,  True],
       [False,  True],
       ...,
       [ True, False],
       [ True,  True],
       [False, False]], shape=(10000, 2))

In [71]:
sim_flips = pd.DataFrame(
    {"Choice A": np.sum((np.random.rand(N,2) < p) * 10, axis=1)})
sim_flips

      Choice A
0            0
1            0
2           10
3           10
4           10
...        ...
9995        20
9996        20
9997        10
9998        20
9999         0

[10000 rows x 1 columns]

## Choice B:

$\large Y_B = \sum\limits_{i=1}^{20} X_i$

In [72]:
sim_flips["Choice B"] = np.sum((np.random.rand(N,20) < p), axis=1)
sim_flips

      Choice A  Choice B
0            0        13
1            0         8
2           10        11
3           10         8
4           10        11
...        ...       ...
9995        20        11
9996        20        11
9997        10         5
9998        20         8
9999         0        10

[10000 rows x 2 columns]

## Choice C:

$\large Y_C = 20 X_1$

In [73]:
sim_flips["Choice C"] = 20  * (np.random.rand(N,1) < p) 
sim_flips

      Choice A  Choice B  Choice C
0            0        13         0
1            0         8         0
2           10        11         0
3           10         8        20
4           10        11         0
...        ...       ...       ...
9995        20        11        20
9996        20        11        20
9997        10         5        20
9998        20         8         0
9999         0        10        20

[10000 rows x 3 columns]

<br/>
If you're curious as to what these distributions look like, I've simulated some populations:

In [74]:
px.histogram(sim_flips.melt(), x="value", facet_row="variable", 
             barmode="overlay", histnorm="probability",
             title="Empirical Distributions",
             width=600, height=600)

In [75]:
pd.DataFrame([
    sim_flips.mean().rename("Mean"),
    sim_flips.var().rename("Var"),
    np.sqrt(sim_flips.var()).rename("SD")
])

       Choice A  Choice B    Choice C
Mean  10.012000  9.986200   10.086000
Var   50.424898  5.000310  100.002604
SD     7.101049  2.236137   10.000130

______

## Visualizing the Binomial Distribution

> This section replicates figures from the lecture slides. We won't cover it together.

The binomial distribution provides the probability of $y$ successes among $n$ trials,
where each trial has $p$ probability of success:

$$
P(Y=y) = \binom{n}{y} p^y (1-p)^{n-y}
$$

Equivalently, a binomial RV is a sum of $n$ Bernoulli RVs, each with probability $p$ of success.

We can visualize the binomial distribution for different combinations of
$n$ and $p$, as a function of $y$:

In [76]:
# Make a grid plots the binomial distribution for p = 0.5 and n = [1, 2, 3, 10, 100]

# np.math.comb(n,k) gives the binomial coefficient for "n choose k"
def binom(n, k, p): 
  return np.math.comb(n, k) * p**k * (1-p)**(n-k)

n_values = [1, 2, 3, 10, 20, 100]

binom_df = pd.DataFrame({
    "n": np.concatenate([[n] * (n+1) for n in n_values]),
    "y": np.concatenate([np.arange(n+1) for n in n_values]),
    "P(Y=y)": [binom(n, y, 0.5) for n in n_values for y in range(n+1)]
})

fig = px.bar(binom_df, x="y", y="P(Y=y)", 
             facet_col="n", facet_col_wrap=3,
             facet_col_spacing=0.1, facet_row_spacing=0.15)

# Show axis ticks on all subplots
fig.update_yaxes(matches=None, showticklabels=True)
fig.update_xaxes(matches=None, showticklabels=True)

# Increase font size
fig.update_layout(font=dict(size=18))

# Increase size of figure
fig.update_layout(width=1000, height=600)

fig.show()

AttributeError: module 'numpy' has no attribute 'math'

<br/><br/><br/>

---

# From Population to Sample

> This section replicates findings from the lecture. We won't cover it together.

Remember the population distribution we looked at earlier:

In [ ]:
dist_df

In [ ]:
# A population generated from the distribution
N = 100000
all_samples = np.random.choice(dist_df["x"], N, p=dist_df["P(X = x)"])
sim_pop_df = pd.DataFrame({"X": all_samples})
sim_pop_df

<br/><br/><br/>
Suppose we draw a sample of size 100 from this giant population.

We are performing **Random Sampling with Replacement:** `df.sample(n, replace=True)` ([link](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sample.html))

In [ ]:
n = 100      # Size of our sample
sample_df = (
             sim_pop_df.sample(n, replace=True)
             # Some reformatting below
             .reset_index(drop=True)
             .rename(columns={"X": "X"})
            )
sample_df

Our **sample distribution** (n = 100):

In [ ]:
px.histogram(sample_df, x="X", histnorm="probability", title="Sample (n = 100)")

<br/>

Compare this to our **original population** (N = 80,000):

In [ ]:
px.histogram(sim_df, x="X", histnorm="probability", title="Population of X")

In [ ]:
pd.DataFrame(
    {"Sample": [sample_df["X"].mean(), sample_df["X"].var(), np.sqrt(sample_df["X"].var())],
     "Population": [sim_df["X"].mean(), sim_df["X"].var(), np.sqrt(sim_df["X"].var())]})

In [ ]:
# Three different distributions of X where E(X)=25

# First distribution
dist1_df = pd.DataFrame({"x": [20, 25, 30],
                         "P(X = x)": [0.2, 0.5, 0.2]})
# Second distribution -- really skewed
dist2_df = pd.DataFrame({"x": [0, 25, 50],
                         "P(X = x)": [0.49, 0.02, 0.49]})
# Third distribution -- skewed left
dist3_df = pd.DataFrame({"x": [0, 25, 150],
                         "P(X = x)": [0.5, 0.4, 0.1]})

fig, axs = plt.subplots(1, 3, figsize=(10, 2))
for i, dist_df in enumerate([dist1_df, dist2_df, dist3_df]):
    sns.barplot(x="x", y="P(X = x)", data=dist_df, ax=axs[i], color="skyblue")

plt.tight_layout()

plt.show()